### ISSUE TITLE
v1.3 User Stories and tasks

### ISSUE THREAD

**Issue by sivayogasubramanian** [AY2122S1-CS2103T-W16-2/tp#102]
## User Stories that need to be completed by the end of v1.3

- [ ] As a home chef, I can add a new recipe so that I can copy details from a recipe to easily fill up the details of an order.
- [ ] As a home chef, I can delete a recipe so that I can delete unused recipes.
- [ ] As a home chef, I can edit a recipe so that I can add new ingredients used in the recipe or edit the quantity of existing ingredients. 
- [ ] As a home chef, I can find a recipe so that I can reference the recipe when creating an order.
- [ ] As a home chef, I can view all recipes so that I can see all the current recipes used.
- [ ] As a home chef, I can detect duplicate recipes so that I do not clutter the application with duplicate recipes.
- [ ] As a home chef, I can view my most popular clients so that I can reinforce my business relationship with my popular clients.
- [ ] As a home chef, I can view my most popular recipes so that I can focus on growing my business with the popular recipes.
- [ ] As a home chef, I can view my monthly revenue so that I can tell if my business is growing.
