### ISSUE TITLE
v1.2 User Stories and tasks

### ISSUE THREAD

**Issue by sivayogasubramanian** [AY2122S1-CS2103T-W16-2/tp#61]
## User Stories that need to be completed by the end of v1.2

- [x] #62
- [x] #63
- [x] #75
- [x] #86
- [x] #73
- [x] As a home chef, I can detect duplicate ingredients so that I do not clutter the application with duplicate ingredients.
- [x] As a home chef, I can add new clients so that I can easily fill up the details of an order.
- [x] As a home chef, I can delete a client so that I can remove former clients.
- [x] As a home chef, I can edit a client so that I can update their contact information.
- [x] #64
- [x] As a home chef, I can view all clients so that I can view all my current clients.
- [x] As a home chef, I can detect duplicate clients so that I do not clutter the application with duplicate clients.
- [x] #60
- [x] #90
- [x] #89
- [x] #68
- [x] #71
- [x] #87
- [x] #88

## View tasks
- [x] #65
- [x] #73

## General tasks after the user stories above are fully implemented
- [x] #76
- [x] #81
- [x] #77
